services:
  nezha-agent:
    image: hzct123/nezha:agent
    container_name: nezha-agent
    network_mode: host
    restart: always # 开机启动
    pull_policy: always # 可选：始终拉取最新镜像
    user: 65533:65533 # 可以把数字换成其他的避免和其他容器或软件同用户
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
    environment:
      - HOST_PROC=/host/proc
    volumes:
      - ./nezha-agent:/etc/nezha-agent
      # 主系统设置：chown -R 65533:65533 /完整映射目录/nezha-agent 数字需要和user一致。
      - /proc:/host/proc:ro
      - /etc/os-release:/etc/os-release:ro
    command: -c /etc/nezha-agent/config.yml
    # https://nezha.wiki/guide/agent.html 打开往下滑到“在 OpenWrt 系统中安装 Agent”，从“3.创建配置文件”开始按照文档创建配置文件。
    # 配置文件参数说明：https://nezha.wiki/configuration/agent.html
